### ISSUE TITLE
installation of "laas" packages overwrites ros sources

### ISSUE THREAD

**Issue by vincentberenz** [machines-in-motion/ubuntu_installation_scripts#12]
See :  

https://github.com/machines-in-motion/ubuntu_installation_scripts/blob/be3e642c2b18f8f16e9db22a6c96bb2b669c8ff1/official/ubuntu_16_04/docker/laas/Dockerfile#L15****

Would replacing ">" by ">>" do it, or is there a reason for this overwrite ?

**Comment by MaximilienNaveau** [comment]
No big deal we will create a dedicated .list file which is not in ros-latest

**Comment by luator** [comment]
I agree with Max.  Using `>>` would probably fix he issue but the proper solution is to not add this in the "ros-latest.list" but add a separate "robotpkg.list".

**Comment by MaximilienNaveau** [comment]
problem solved!
https://github.com/machines-in-motion/ubuntu_installation_scripts/commit/7e7f6d5864a6405c6f0880a1d26729b48a2fad8b
