### ISSUE TITLE
Update rt_preempt kernel version to latest stable release

### ISSUE THREAD

**Issue by jviereck** [machines-in-motion/ubuntu_installation_scripts#4]
The current rt_preempt install script installs kernel `4.14.78-rt47`. The latest stable rt_preempt version (at point of writing) is [4.19.72-rt26](http://cdn.kernel.org/pub/linux/kernel/projects/rt/4.19/).

**Comment by MaximilienNaveau** [comment]
I think your comment is related to https://github.com/machines-in-motion/ubuntu_installation_scripts/issues/10.

- 1. It is not mandatory to have the latest rt_preempt release if we do not have dependencies or real-time issues.
- 2. We should try to update the patch only upon updating the Ubuntu OS (every 2 years).
